import {
  Bucket,
  ParentRequest,
  PendingWant,
  Transaction,
  Trip,
  SAVINGS_BUCKET_ID,
  initialBuckets,
} from "@/lib/bucket-store";

/**
 * Everything that is genuinely *about the money*. This object is the unit of
 * persistence in Phase 2, so it must stay JSON-serializable: no React components,
 * no DOM nodes, no functions.
 *
 * Presentation state (which tab is open, whether a coin is mid-flight, which card is
 * pulsing) deliberately lives outside this, in the provider. Mixing it in is what makes
 * a store impossible to write to a database.
 */
export type BucketState = {
  buckets: Bucket[];
  startingBalances: Record<string, number>;
  transactions: Transaction[];
  pending: PendingWant[];
  parentRequests: ParentRequest[];
  savedByPause: number;
  trip: Trip | null;
};

export const createInitialState = (): BucketState => ({
  buckets: initialBuckets,
  startingBalances: Object.fromEntries(initialBuckets.map((b) => [b.id, b.balance])),
  transactions: [],
  pending: [],
  parentRequests: [],
  savedByPause: 0,
  trip: null,
});

/**
 * Actions carry fully-formed records. Ids and timestamps are generated by the caller,
 * never in here — a reducer that reads `crypto.randomUUID()` or the clock cannot be
 * replayed against a fixture, which is exactly what the Phase 8 evaluation set needs.
 */
export type BucketAction =
  | { type: "HYDRATE"; state: BucketState }
  | { type: "RESET" }
  | { type: "CONFIRM_PURCHASE"; transaction: Transaction }
  | { type: "SLEEP_ON_IT"; item: PendingWant }
  | { type: "REMOVE_PENDING"; id: string }
  | { type: "RESTORE_PENDING"; item: PendingWant }
  | { type: "CREDIT_SAVINGS"; amount: number }
  | { type: "DEBIT_SAVINGS"; amount: number }
  | { type: "CREATE_BUCKET"; bucket: Bucket }
  | { type: "SET_CHILD_LIMIT"; limit: number | null }
  | { type: "PARENT_REQUEST_CREATE"; request: ParentRequest }
  | { type: "PARENT_REQUEST_RESOLVE"; id: string; status: "approved" | "denied" }
  | { type: "SET_TRIP"; trip: Trip | null };

export function bucketReducer(state: BucketState, action: BucketAction): BucketState {
  switch (action.type) {
    case "HYDRATE":
      return action.state;

    case "RESET":
      return createInitialState();

    case "CONFIRM_PURCHASE": {
      const { transaction } = action;
      return {
        ...state,
        buckets: state.buckets.map((b) =>
          b.id === transaction.bucketId ? { ...b, balance: b.balance - transaction.amount } : b,
        ),
        transactions: [transaction, ...state.transactions],
      };
    }

    case "SLEEP_ON_IT":
      return { ...state, pending: [action.item, ...state.pending] };

    case "REMOVE_PENDING":
      return { ...state, pending: state.pending.filter((p) => p.id !== action.id) };

    case "RESTORE_PENDING":
      return { ...state, pending: [action.item, ...state.pending] };

    /**
     * Releasing a pending want. `startingBalances` moves in step with the balance so the
     * Savings card does not read the incoming money as "spent" on its progress bar.
     */
    case "CREDIT_SAVINGS":
      return {
        ...state,
        buckets: state.buckets.map((b) =>
          b.id === SAVINGS_BUCKET_ID ? { ...b, balance: b.balance + action.amount } : b,
        ),
        startingBalances: {
          ...state.startingBalances,
          [SAVINGS_BUCKET_ID]: (state.startingBalances[SAVINGS_BUCKET_ID] ?? 0) + action.amount,
        },
        savedByPause: state.savedByPause + action.amount,
      };

    /** Undo of the above. The clamps match the prototype's behaviour exactly. */
    case "DEBIT_SAVINGS":
      return {
        ...state,
        buckets: state.buckets.map((b) =>
          b.id === SAVINGS_BUCKET_ID ? { ...b, balance: b.balance - action.amount } : b,
        ),
        startingBalances: {
          ...state.startingBalances,
          [SAVINGS_BUCKET_ID]: Math.max(
            0,
            (state.startingBalances[SAVINGS_BUCKET_ID] ?? 0) - action.amount,
          ),
        },
        savedByPause: Math.max(0, state.savedByPause - action.amount),
      };

    case "CREATE_BUCKET":
      return {
        ...state,
        buckets: [...state.buckets, action.bucket],
        startingBalances: {
          ...state.startingBalances,
          [action.bucket.id]: action.bucket.balance,
        },
      };

    case "SET_CHILD_LIMIT":
      return {
        ...state,
        buckets: state.buckets.map((b) =>
          b.ownerType === "child" ? { ...b, limit: action.limit } : b,
        ),
      };

    case "PARENT_REQUEST_CREATE":
      return { ...state, parentRequests: [action.request, ...state.parentRequests] };

    case "PARENT_REQUEST_RESOLVE":
      return {
        ...state,
        parentRequests: state.parentRequests.map((r) =>
          r.id === action.id ? { ...r, status: action.status } : r,
        ),
      };

    case "SET_TRIP":
      return { ...state, trip: action.trip };

    default:
      return state;
  }
}
